config/routes.rb
Rails.application.routes.draw do
  resources :menus
  resources :records
  resources :competitions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/competition.rb
class Competition < ApplicationRecord
    has_many :records
end

app/models/menu.rb
class Menu < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/record.rb
class Record < ApplicationRecord
    belongs_to :competition
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController

  before_action :set_competiton, only: [:show, :edit, :update]
  
  def index
    @competitions = Competition.all
  end

  def new
    @competition = Competition.new
  end

  def create
    @competition = Competition.new(competition_params)
    @competition.save
    redirect_to competition_path(@competition)
  end

  def show
    @records = @competition.records.all
  end

  def edit
  end

  def update
    @competition.update(competition_params)
    redirect_to competition_path(@competition)
  end

  private
  def competition_params
    params.require(:competition).permit(:name, :summary)
  end

  def set_competiton
    @competition = Competition.find(params[:id])
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update]
  
    def index
      @menus = Menu.all
      @menu_date = Menu.all
    end
  
    def new
      @menu = Menu.new
    end
    require 'pry'
    def create
      @menu = Menu.new(menu_params)
      binding.pry
      @menu.save
      redirect_to menus_path
    end
  
    def show
    end
  
    def edit
    end
  
    def update
      @menu.update(menu_params)
      redirect_to menus_path
    end
  
    private
    def menu_params
      params.require(:menu).permit(:name, :detail, :total_distance, :image)
    end
  
    def set_menu
      @menu = Menu.find(params[:id])
    end
  
  
  end
  

app/controllers/records_controller.rb
class RecordsController < ApplicationController
before_action :set_record, only: [:show, :edit, :update]

  def index
    @records = Record.all
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(recode_params)
    @record.save
    redirect_to record_path(@record)
  end

  def show
  end

  def edit
  end

  def update
    @record.update
    redirect_to record_path(@record)
  end

  private
  def recode_params
    params.require(:record).permit(:name, :competition_id, :total_time,)
  end

  def set_record
    @record = Record.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/competitions/edit.html.erb
<h1>Competitions#edit</h1>
<p>Find me in app/views/competitions/edit.html.erb</p>

app/views/competitions/index.html.erb
<h1>Competitions#index</h1>
<p>Find me in app/views/competitions/index.html.erb</p>

app/views/competitions/new.html.erb
<%= form_for @competition do |f| %>
    name
    <%= f.text_field :name, class:"form-control" %>
    summary
    <%= f.text_field :summary, class:"form-control" %>
    <%= f.submit "create competiton", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
<% end %>

app/views/competitions/show.html.erb
<%= @competition.name %>
<%= link_to 'record', new_record_path %>
<% @records.each do |record| %>
    
     <table>
        <tr>
            <td>  
                <%= link_to record.name, record_path(record) %>
            </td>
            <td>
               <%= record.total_time %>
            </td>
        </tr>
    </table>

    
<% end %>
<%= line_chart @records.pluck(:created_at,:total_time), max: 60,title: "total distance" %>
 <!--x軸y軸の設定はpluck(:x軸,：y軸)でいけるy-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrcPortfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menus/edit.html.erb
<h1>Menus#edit</h1>
<p>Find me in app/views/menus/edit.html.erb</p>

app/views/menus/index.html.erb
<%= link_to 'new', new_menu_path %>
<% @menus.each do |menu| %>
    
     <table>
        <tr>
            <td>  
                <%= link_to menu.name, menu_path(menu) %>
            </td>
            <td>
               <%= menu.total_distance %>
            </td>
        </tr>
    </table>

    
<% end %>
<%= line_chart @menu_date.pluck(:created_at,:total_distance), max: 12000,title: "total distance" %>
 <!--x軸y軸の設定はpluck(:x軸,：y軸)でいけるy-->

app/views/menus/new.html.erb
<%= form_for @menu do |f| %>
    メニュー名
    <%= f.text_field :name, class:"form-control" %>
    内容
    <%= f.text_field :detail, class:"form-control" %>
    距離
    <%= f.number_field :total_distance, class:"form-control" %>
    <%= f.label :image %>
    <%= f.file_field :image %>


    <%= f.submit "create menu", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
<% end %>

app/views/menus/show.html.erb
<%= image_tag @menu.image.url %>

app/views/records/edit.html.erb
<h1>Records#edit</h1>
<p>Find me in app/views/records/edit.html.erb</p>

app/views/records/index.html.erb
<h1>Records#index</h1>
<p>Find me in app/views/records/index.html.erb</p>

app/views/records/new.html.erb
<%= form_for @record do |f| %>
    大会
    <%= f.collection_select :competition_id, Competition.all, :id, :name %>
    選手名
    <%= f.text_field :name, class:"form-control" %>
    タイム
    <%= f.number_field :total_time, step: '0.01', class:"form-control" %>


    <%= f.submit "create record", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
<% end %>

app/views/records/show.html.erb
<h1>Records#show</h1>
<p>Find me in app/views/records/show.html.erb</p>